import {
  BellRing,
  Blocks,
  ClipboardCheck,
  HomeIcon,
  House,
  InfoIcon,
  Replace,
  SettingsIcon,
  StickyNote,
  University,
  User,
  UserCog,
  UserRoundPen,
  UsersRound,
} from "lucide-react";

export const navItems = [
  { to: "/", label: "Home", icon: House },
  { to: "/about", label: "About", icon: InfoIcon },
  { to: "/posts", label: "Posts", icon: StickyNote },
  { to: "/status", label: "Status", icon: ClipboardCheck },
  { to: "/user", label: "User", icon: User },
  { to: "/user/123", label: "User/123", icon: UserCog },
  { to: "/user/123/edit", label: "User/123/edit", icon: UsersRound },
  { to: "/ChildOfLayout", label: "ChildOfLayout", icon: Blocks },
  { to: "/ChildOfLayout2", label: "ChildOfLayout2", icon: Replace },
  { to: "/ChildOfLayout3", label: "ChildOfLayout3", icon: University },
  { to: "/settings", label: "Settings", icon: SettingsIcon },
  {
    to: "/settings/notifications",
    label: "Notifications",
    icon: BellRing,
  },
  { to: "/settings/profile", label: "Profile", icon: UserRoundPen },
];
